import Card from "../../components/common/Card";

export default function WeeklyPlanPage() {
  return (
    <Card title="Weekly Plan" subtitle="Topic focus + daily structure generated by AI.">
      <ul className="list-disc space-y-2 pl-5 text-sm text-slate-300">
        <li>Week focus: Algebraic fractions.</li>
        <li>Mon-Fri exercises adapt from basic to advanced.</li>
        <li>Max load capped at 3 exercises/day.</li>
      </ul>
    </Card>
  );
}
